version: '3.8'

services:
  food-search-app:
    image: food-search-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SOLR_HOST="http://solr:8983/solr/food_collection"
      - SOLR_PORT=8983
    depends_on:
      - solr
    networks:
      - app-network

  solr:
    image: solr:9.3
    ports:
      - "8983:8983"
    environment:
      - SOLR_JAVA_MEM=-Xms512m -Xmx512m
    volumes:
      - solr-data:/var/solr
    command: solr-precreate food_collection
    networks:
      - app-network

volumes:
  solr-data:

networks:
  app-network:
    driver: bridge